### ISSUE TITLE
[Feature Request] Option to send OCR text through websocket instead of copying to clipboard

### ISSUE THREAD

**Issue by MobApache** [matt-m-o/YomiNinja#1]
Windows clipboard is not designed to be both written to and read from by applications on the fly, so it's not equipped to handle the workload, resulting in delay when using the application with a texthooking page and a clipboard inserter, while if you use a websocket it's pretty much instant.

**Comment by matt-m-o** [comment]
Thank you for your suggestion.

To clarify, the WebSocket you mentioned should be compatible with applications similar to [texthooker-ui](https://github.com/Renji-XD/texthooker-ui), correct? 
If that's the case, I'll work on implementing a WebSocket with the same message pattern.

**Comment by MobApache** [comment]
Yes, that's the case

**Comment by matt-m-o** [comment]
@MobApache 

The latest release, v0.2.1, exposes a WebSocket on port 6677 and emits the copied text. Give it a try and let me know if it works as expected.

**Comment by MobApache** [comment]
Working fine, thank you for the feature
