### ISSUE TITLE
0.3.1 slow/delayed ocr processing

### ISSUE THREAD

**Issue by TestSubject-999** [matt-m-o/YomiNinja#10]
Wanted to open an issue here just in case, but a few people are having issues with the ocr results being delayed on the most recent update. Switching back to 0.2.1 everything seems fine though.

**Comment by matt-m-o** [comment]
That's strange. What CPU are you using?
Also, please provide a screenshot of the OCR Engine settings.

**Comment by matt-m-o** [comment]
I believe I was able to reproduce the issue. It seems that sometimes there is a problem preventing it from fully loading on the first launch, leaving a YomiNinja instance running in the background.


Please try the following steps:

1. Uninstall YomiNinja
2. Install version 0.3.1
3. Open the task manager (Ctrl + Shift + Esc)
4. Find and kill all YomiNinja processes by clicking on "End task"
5. Launch YomiNinja

Let me know if this resolves the issue.

**Comment by matt-m-o** [comment]
Are you using an antivirus? If yes, which one? Disabling the antivirus also seems to help in my case.
