### ISSUE TITLE
JPDBreader support

### ISSUE THREAD

**Issue by kokoropaint** [matt-m-o/YomiNinja#12]
[JPDBreader](https://github.com/max-kamps/jpd-breader) is a browser extension that parses web pages through JPDB and provides furigana+a popup dictionary. The biggest benefit of using it is that you can connect your JPDB account to it and quickly add words to your flashcard deck, plus easily visualize which words you do/don't already know with highlighting. (you can also customize things like not showing furigana for known words, etc.)
This extension makes using JPDB as a learning aid very seamless (similar to connecting Yomichan+Anki) so supporting it or something similar in YomiNinja would be great :)

**Comment by matt-m-o** [comment]
I wasn't aware of this extension, but it seems quite useful. Thanks for the suggestion! Accessing the extension settings was a bit tricky, but I managed to do so.  I've already made some adjustments to the overlay to handle furigana, and now I need to ensure that the extension settings menu loads correctly.

![JPDB Reader](https://github.com/matt-m-o/YomiNinja/assets/25914763/0ce58bdc-20df-4dae-8430-42e7e3ea8c96)

**Comment by madmalkav** [comment]
Looks great!

**Comment by kokoropaint** [comment]
Tried testing out 0.5.1's expanded extension support earlier for this. After installing I'm having issues getting to JPDBreader's settings page, which is required to input your API key. The popup window for the extension is somewhat buggy (twitches/flickers on the screen), and if I manage to click through to the settings button the popup for it immediately closes.

**Comment by matt-m-o** [comment]
@kokoropaint 
The v0.5.1 doesn't include support for JPDBReader, so you may encounter many bugs. However, you can attempt to set the API key by right-clicking on the **Settings** link and selecting **Open link in a new window**. Although the "window" may appear quite small, you should still be able to set the key from there.

![image](https://github.com/matt-m-o/YomiNinja/assets/25914763/1836617d-627b-4351-9cbd-f533d05031b3)

**Comment by madmalkav** [comment]
Should be completely integrated on latest version. Can you please try and, if everything is qorking OK for you, close the ticket?

**Comment by kokoropaint** [comment]
Did some light testing and everything looks good! :)
