### ISSUE TITLE
New way to implement Google's OCR

### ISSUE THREAD

**Issue by jp-man25** [matt-m-o/YomiNinja#18]
Someone recently found a way to implement Google Lens into their OCR program. Lens can be used unlimitedly without the need of an API key, unlike with the normal Google Vision implementation. It seems to work very well for now, would be very nice if it could be implemented in Yomininja. Here's the Github: https://github.com/AuroraWright/owocr

**Comment by matt-m-o** [comment]
Thank you for bringing this up! Unfortunately, I couldn't include it in v0.6 due to time constraints, as the results need to be parsed in a completely different way. However, I'll make an effort to add support for Google Lens soon, possibly v0.6.x.

**Comment by matt-m-o** [comment]
Implemented in [v0.6.4+](https://github.com/matt-m-o/YomiNinja/releases/tag/v0.6.4)
