### ISSUE TITLE
Installing Yomitan via Zip completely destroys YomiNinja Install.

### ISSUE THREAD

**Issue by Maestar** [matt-m-o/YomiNinja#24]
I've downloaded yomitan via CRX Extractor/Downloader and attempted to install it into the latest version of YomiNinja, upon doing so the yomininja gui has become completely unresponsive. Closing the program and relaunching it does not solve the issue, it remains unresponsive. 

I've uninstalled YomiNinja, reinstalled it and tried to install the extension again with the exact same result just to check for a fluke but the results remain the same, the program becomes permanently unresponsive.

EDIT: I'm leaving this up just incase you do want to bring yomitan into the application itself in the future, but I am a complete idiot and forgot you have provided another way to use yomitan. I was so excited to see the browser extension installer I temporarily forgot how to read.

**Comment by matt-m-o** [comment]
I've addressed this issue in the upcoming [v0.6 release](https://www.patreon.com/posts/yomininja-v0-6-97434526), which should be available to everyone very soon. You'll be able to install Yomitan without experiencing any side effects. Thanks!

**Comment by madmalkav** [comment]
Can you please try the last version and confirm if the problem persists?
