### ISSUE TITLE
Maintain focus on the previous window.

### ISSUE THREAD

**Issue by TestSubject-999** [matt-m-o/YomiNinja#3]
Currently when you initiate OCR the overlay becomes the focused window. For some games this is an issue because you lose control of the game unless you tab back in. If possible having it not steal the focus away would be beneficial.

**Comment by TestSubject-999** [comment]
Maybe the option to choose behavior would be best.

**Comment by matt-m-o** [comment]
I'll run some tests and try to find the best way to address this.
Are you using the "Always on top" option?

Thank you for your suggestion.

**Comment by TestSubject-999** [comment]
Yeah I'm using always on top.

**Comment by matt-m-o** [comment]
[Version 0.4.1](https://github.com/matt-m-o/YomiNinja/releases/tag/v0.4.1) has been released, which includes an option to address your request.
To access it, navigate to the app **Settings** > **Overlay Behavior** > **Show overlay without stealing focus**.
Please give it a try and let me know how it works for you.

**Comment by TestSubject-999** [comment]
Just tested it and it works like a charm when used in conjunction with copy on hover. This can really save users the pain of doing a thousand alt tabs on certain games. Thanks a bunch!

**Comment by matt-m-o** [comment]
Thank you for your feedback and suggestions!
I understand that depending solely on "copy on hover" might be a bit cumbersome. Would adding a hotkey for copying text be helpful?

**Comment by TestSubject-999** [comment]
A hotkey option might actually be helpful people who dislike copy on hover, but personally I actually like copy on hover

If you are looking for more suggestions, I think it might be interesting to have a hotkey that has an adjustable "timing" in which the ocr'd content is displayed and then cleared. 
I am currently using a macro on my mouse to create this function, which gives me a roughly 5 second window to hover what I want before auto clearing it, in order to save me the trouble of doing it every time manually. However not everyone has a mouse with macro functions, and some mice have some wonky macro implementation anyways.
