### ISSUE TITLE
Some improvements and bugs

### ISSUE THREAD

**Issue by Kalleo1** [matt-m-o/YomiNinja#9]
**Some improvements:**

1. Option to clear overlay when clicking outside the textbox instead of having to press Alt + V.
2. Option to ignore non-japanese characters when your OCR language is set to Japanese.
3. Better* Support for vertical text.
	- If you try it on manga it gets really messy with all the textboxes and all
4. Let the user choose the drive they want to install YomiNinja.
	- This is something necessary for people with limited storage space on the main drive, especially if you add more OCR engines in the future, which will take up more space.
5. Be able to remove the border around the screen and around textboxes .
	- If I set it to 0, it still continues to show the border
	- Maybe adding a keybind to show and hide the borders would not be a bad idea.
6. Option to put the program in the system tray when you minimize it.
	- This is not something REALLY necessary but it more for esthetics.
7. Option to toggle Show/Hide the overlay.
	- I don't know if Alt + C already does this, if it does, it's not working for me.
	- This can be related to the improvement number 5 (but here the text would also be hidden)

**Some bugs:**
_Just for context, I'm using windows 11._

1. The option to copy text on click does not work.
	- instead, it loses focus from the overlay when I click on the textbox
2. The default keybind to copy text (C) does not work on some browsers.
 	- I tested with Chrome and Edge, and it does not work, but with Opera, it works. 
	- Instead, I need to press Alt + C to copy the text (which conflicts with the default keybind to show the overlay).
	- I can just change the keybinds to other keys, but I'm reporting this so you can know and maybe change the defaults to something else.

-------------------------------

I want to thank you for the great work you're doing here. I really think that YomiNinja can be a breakthrough for learning Japanese with games and other media, especially when we have more OCR engines and automatic detection. But the program is already really good the way it is. Good job, dude!

**Comment by matt-m-o** [comment]
Thank you for your comprehensive feedback. I appreciate the time and effort you've put into detailing these suggestions.
Here's an update on some of the points you raised.

Improvements:

3. The rendering of textboxes has been significantly enhanced in v0.5. However, for an optimal manga experience, the current OCR engine might require further refinement or the introduction of another OCR engine.

4. Initially, I maintained a consistent installation directory for all users to streamline troubleshooting. Given that most issues have now been addressed, I'm planning to introduce customizable installation directories soon.

5. The issue with the border was addressed in version 0.4.1. You can now set the border width to 0, and it should disappear. As for the keybind, I'll consider adding it in a future update.

7. As you pointed out, Alt + C currently only shows the overlay. I'll work on implementing a toggle functionality for this hotkey.

<br>
Bugs:

1. It's possible that click-through was enabled in the settings. Try v0.4.1 with the click-through in "auto" mode. It should work as expected.

3. Given that "copy text on click" is functioning correctly in recent versions, I disabled the hotkey for copying text. However, if there's a compelling reason to reintroduce it, I'll certainly consider doing so.

I hope to address everything as soon as possible. Please let me know if v0.4.1 is working well for you. Thank you for the positive feedback!

**Comment by Kalleo1** [comment]
From the tests I've done so far, everything is working well now. Thank you for your answer, I appreciate it.

**Comment by madmalkav** [comment]
Can you confirm if this is solved for you on the last version and if so close the ticket? If not, I would like to suggest to close this one anyway and create a ticket for each single bug/feature request so tracking each o e of them is easier
